fail_fast: true
repos:
    - repo: https://github.com/PyCQA/bandit
      rev: 1.7.9
      hooks:
          - id: bandit
            args: ["-c", "pyproject.toml"]
            additional_dependencies: ["bandit[toml]"]
    - repo: https://github.com/PyCQA/pydocstyle
      rev: 6.3.0
      hooks:
          - id: pydocstyle
            additional_dependencies: ["toml"]

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: trailing-whitespace
          - id: check-toml
    - repo: https://github.com/psf/black
      rev: 24.4.2
      hooks:
          - id: black
    - repo: https://github.com/PyCQA/flake8
      rev: 7.1.0
      hooks:
          - id: flake8
            additional_dependencies: [flake8-pyproject]
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.10.1
      hooks:
          - id: mypy
            additional_dependencies: [types-requests]
            exclude: ^tests/
    - repo: local
      hooks:
          - id: pytest
            name: pytest
            stages: [commit]
            language: python
            entry: pytest ./tests
            types: [python]
            pass_filenames: false
            always_run: true
    - repo: https://github.com/commitizen-tools/commitizen
      hooks:
        - id: commitizen
        - id: commitizen-branch
          stages:
            - push
      rev: v3.28.0
