name: pre-commit-run

on:
  push:
  pull_request:
  merge_group:

jobs:

  pre-commit-run:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies with poetry
        run: |
          pip install poetry
          poetry install --with dev,test

      - name: Run pre-commit
        run: |
          source $(poetry env info --path)/bin/activate
          pre-commit run --all-files --show-diff-on-failure --color=always
